on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '@i18n'
      - name: Invoke i18n script webhook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{secrets.WEBHOOK_URL}}
          webhook_secret: ${{secrets.WEBHOOK_SECRET}}
          
