on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '@i18n'
      - name: Invoke i18n workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Repo Dispatch
          repo: Fernker/i18nTest2
          token: ${{ secrets.ACCESS_TOKEN}}
          ref: ${{github.ref}}
          inputs: '{"message": ${{process.env.GITHUB_HEAD_REF}}}' 
#      - name: Invoke i18n script
#        uses: peter-evans/repository-dispatch@v2
#        with:
#          token: ${{ secrets.ACCESS_TOKEN }}
#          repository: Fernker/i18nTest2
#          event-type: my-event
#          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
          
          
